// Writes src/abi.ts from Foundry's build output (../out), so the front-end never carries a hand-copied ABI
// that could drift from the deployed contracts. Run `forge build` first.
import { readFileSync, writeFileSync } from "node:fs";

const pick = (file, name) => JSON.parse(readFileSync(new URL(`../../out/${file}/${name}.json`, import.meta.url))).abi;
const out = [
  "// Generated by scripts/gen-abi.mjs from Foundry's build output. Do not edit.",
  `export const perpEngineAbi = ${JSON.stringify(pick("PerpEngine.sol", "PerpEngine"))} as const;`,
  `export const consensusFeedAbi = ${JSON.stringify(pick("ConsensusFeed.sol", "ConsensusFeed"))} as const;`,
  `export const priceSourceAbi = ${JSON.stringify(pick("PythPriceSource.sol", "PythPriceSource"))} as const;`,
  `export const testUsdcAbi = ${JSON.stringify(pick("TestUSDC.sol", "TestUSDC"))} as const;`,
  "",
].join("\n");
writeFileSync(new URL("../src/abi.ts", import.meta.url), out);
console.log("wrote src/abi.ts");
